# Clear Memory
rm(list = ls(all.names = TRUE))
# Import Libraries in R
library(plyr) # for renaming
# Printing
library("xtable")
options(xtable.floating = FALSE)
options(xtable.timestamp = "")
# options defaults
options(digits=2)
options(scipen=999)

# Definitions
.str <- function(x){
  # Modified str() to display all list elements within a level.
  # Charalambos Themistocleous 2015
  str(x, list.len=length(x))
}

# Get the trimmed mean predefined value at the 10%
mean1 <- function(x,...){
  mean(x,trim=.1)
}

# Import Database in R
v <- read.table("all_sounds.csv", sep=",", header = T)
.str(v)


# ADDING NEW COLUMNS ------------------------------------------------------



v$therapy_scored <- revalue(v$speaker,c("ABK" = "x",
                                        "ACY" = NA,
                                        "AGG" = NA,
                                        "BIN" = "aos",
                                        "BLR" = "x",
                                        "CBN" = NA,
                                        "CBT" = "x",
                                        "CCD" = NA,
                                        "CKI" = "x",
                                        "DCN" = "x",
                                        "DEK" = "x",
                                        "DME" = NA,
                                        "DNE" = "x",
                                        "DPD" = "x",
                                        "DPZ" = "x",
                                        "DRS" = "x",
                                        "DUE" = "x",
                                        "EAE" = "x",
                                        "EBG" = NA,
                                        "ERM" = "x",
                                        "GSH" = "aos",
                                        "IJN" = "x",
                                        "JBN" = "aos",
                                        "JEE" = "x",
                                        "JHR" = NA,
                                        "JJI" = "aos",
                                        "JPS" = "aos",
                                        "JRA" = "x",
                                        "JSS" = "x",
                                        "JWE" = "x",
                                        "KBG" = NA,
                                        "LCR" = NA,
                                        "LRW" = "x",
                                        "MOR" = NA,
                                        "MPI" = "x",
                                        "MSM" = "aos",
                                        "MVR" = "x",
                                        "NCG" = "x",
                                        "RFH" = "x",
                                        "RLN" = "x",
                                        "SFY" = NA,
                                        "SRI" = "aos",
                                        "SRR" = NA,
                                        "TBE" = "x",
                                        "bnr" = "x",
                                        "cce" = NA,
                                        "cdy" = NA,
                                        "cke" = "x",
                                        "DDN" = NA,
                                        "DRY" = "aos",
                                        "DTL" = NA,
                                        "GFS" = NA,
                                        "HAH" = NA,
                                        "jjn" = "x",
                                        "jka" = "x",
                                        "jrd" = "x",
                                        "jre" = "x",
                                        "kce" = "x",
                                        "KEY:" = NA,
                                        "lrl" = "x",
                                        "pzr" = "aos",
                                        "rbg" = "x",
                                        "rcl" = "x",
                                        "RJN" = NA,
                                        "rvt" = "aos",
                                        "RWT" = "x",
                                        "SAS/SPA" = NA,
                                        "SCN" = NA,
                                        "skr" = "x",
                                        "slr" = "x",
                                        "tbd" = "x",
                                        "tbt" = "x",
                                        'AGS2989' = NA,
                                        "BSS7123" = NA,
                                        "BWS1830" = NA,
                                        "CSZ0789" = NA,
                                        "GFN6532" = NA,
                                        "JRK6031" = NA,
                                        "JSR9493" = NA,
                                        "JTR8536" = NA,
                                        "KGR8179" = NA,
                                        "MBR6656" = NA,
                                        "RBS8706" = NA,
                                        "RPI8252" = NA,
                                        "RSN9920" = NA,
                                        "SLR8021" = NA))



v$first_period_condition <- revalue(v$speaker, c("ABK" = "t",
                                                 "ACY" = NA,
                                                 "AGG" = "t1 IFG/t2 PSTG-IPL",
                                                 "BIN" = "t",
                                                 "BLR" = "t",
                                                 "CBN" = "t",
                                                 "CBT" = "s",
                                                 "CCD" = NA,
                                                 "CKI" = "t",
                                                 "DCN" = "t",
                                                 "DEK" = "t",
                                                 "DME" = "s",
                                                 "DNE" = "s",
                                                 "DPD" = "s",
                                                 "DPZ" = "s",
                                                 "DRS" = "t",
                                                 "DUE" = "t",
                                                 "EAE" = "t",
                                                 "EBG" = NA,
                                                 "ERM" = "t",
                                                 "GSH" = "t",
                                                 "IJN" = "s",
                                                 "JBN" = "t",
                                                 "JEE" = "t",
                                                 "JHR" = "s",
                                                 "JJI" = "s",
                                                 "JPS" = "t",
                                                 "JRA" = "s",
                                                 "JSS" = "s",
                                                 "JWE" = "t",
                                                 "KBG" = "s",
                                                 "LCR" = NA,
                                                 "LRW" = "s",
                                                 "MOR" = NA,
                                                 "MPI" = "s",
                                                 "MSM" = "t",
                                                 "MVR" = "t",
                                                 "NCG" = "s",
                                                 "RFH" = "t",
                                                 "RLN" = "s",
                                                 "SFY" = NA,
                                                 "SRI" = "t",
                                                 "SRR" = "t1 ATL-MTL/t2 AG",
                                                 "TBE" = "s",
                                                 "bnr" = "t",
                                                 "cce" = "t",
                                                 "cdy" = "t",
                                                 "cke" = "s",
                                                 "DDN" = NA,
                                                 "DRY" = "t",
                                                 "DTL" = NA,
                                                 "GFS" = "s",
                                                 "HAH" = NA,
                                                 "jjn" = "s",
                                                 "jka" = "s",
                                                 "jrd" = "t",
                                                 "jre" = "t",
                                                 "kce" = "s",
                                                 "KEY:" = NA,
                                                 "lrl" = "t",
                                                 "pzr" = "s",
                                                 "rbg" = "t",
                                                 "rcl" = "s",
                                                 "RJN" = NA,
                                                 "rvt" = "s",
                                                 "RWT" = "t",
                                                 "SAS/SPA" = "t",
                                                 "SCN" = NA,
                                                 "skr" = "s",
                                                 "slr" = "s",
                                                 "tbd" = "s",
                                                 "tbt" = "t",
                                                 'AGS2989' = NA,
                                                 "BSS7123" = NA,
                                                 "BWS1830" = NA,
                                                 "CSZ0789" = NA,
                                                 "GFN6532" = NA,
                                                 "JRK6031" = NA,
                                                 "JSR9493" = NA,
                                                 "JTR8536" = NA,
                                                 "KGR8179" = NA,
                                                 "MBR6656" = NA,
                                                 "RBS8706" = NA,
                                                 "RPI8252" = NA,
                                                 "RSN9920" = NA,
                                                 "SLR8021" = NA))



v$variant <- revalue(v$speaker, c("ABK" = "n",
                                  "ACY" = "l",
                                  "AGG" = "l",
                                  "BIN" = "naos",
                                  "BLR" = "l",
                                  "CBN" = "n",
                                  "CBT" = "l",
                                  "CCD" = "s",
                                  "CKI" = "n",
                                  "DCN" = "s",
                                  "DEK" = "s",
                                  "DME" = "n",
                                  "DNE" = "l",
                                  "DPD" = "n",
                                  "DPZ" = "n",
                                  "DRS" = "l",
                                  "DUE" = "l",
                                  "EAE" = "s",
                                  "EBG" = "l",
                                  "ERM" = "n",
                                  "GSH" = "naos",
                                  "IJN" = "l",
                                  "JBN" = "naos",
                                  "JEE" = "s",
                                  "JHR" = "l",
                                  "JJI" = "naos",
                                  "JPS" = "naos",
                                  "JRA" = "n",
                                  "JSS" = "l",
                                  "JWE" = "s",
                                  "KBG" = "n",
                                  "LCR" = "l",
                                  "LRW" = "n",
                                  "MOR" = "l",
                                  "MPI" = "l",
                                  "MSM" = "naos",
                                  "MVR" = "l",
                                  "NCG" = "s",
                                  "RFH" = "s",
                                  "RLN" = "naos",
                                  "SFY" = "n",
                                  "SRI" = "naos",
                                  "SRR" = "s",
                                  "TBE" = "l",
                                  "bnr" = "l",
                                  "cce" = "naos",
                                  "cdy" = "naos",
                                  "cke" = "n",
                                  "DDN" = "AD",
                                  "DRY" = "naos",
                                  "DTL" = "l",
                                  "GFS" = "n",
                                  "HAH" = "s",
                                  "jjn" = "n",
                                  "jka" = "s",
                                  "jrd" = "l",
                                  "jre" = "l",
                                  "kce" = "s",
                                  "KEY:" = NA,
                                  "lrl" = "n",
                                  "pzr" = "naos",
                                  "rbg" = "l",
                                  "rcl" = "n",
                                  "RJN" = "n",
                                  "rvt" = "naos",
                                  "RWT" = "n",
                                  "SAS/SPA" = "n",
                                  "SCN" = "too early?",
                                  "skr" = "n",
                                  "slr" = "s",
                                  "tbd" = "l",
                                  "tbt" = "n",
                                  'AGS2989' = "l",
                                  "BSS7123" = "s",
                                  "BWS1830" = NA,
                                  "CSZ0789" = "s",
                                  "GFN6532" = NA,
                                  "JRK6031" = NA,
                                  "JSR9493" = "s",
                                  "JTR8536" = "l",
                                  "KGR8179" = "s",
                                  "MBR6656" = NA,
                                  "RBS8706" = NA,
                                  "RPI8252" = "s",
                                  "RSN9920" = NA,
                                  "SLR8021" = "s"))
                    



v$primary_therapy_score <- revalue(v$speaker,c("ABK" = "written naming (VNT)",
                                               "ACY" = NA,
                                               "AGG" = "fluency (tDCS both times)",
                                               "BIN" = "aos",
                                               "BLR" = "written naming (PNT)",
                                               "CBN" = "written naming (PNT)",
                                               "CBT" = "written naming (VNT)",
                                               "CCD" = "written naming (PNT)",
                                               "CKI" = "written naming (VNT)",
                                               "DCN" = "written naming (PNT)",
                                               "DEK" = "written naming (PNT)",
                                               "DME" = "syntactic",
                                               "DNE" = "written naming (VNT)",
                                               "DPD" = "written naming (VNT)",
                                               "DPZ" = "written naming (VNT)",
                                               "DRS" = "written naming (PNT/VNT)",
                                               "DUE" = "written naming (PNT)",
                                               "EAE" = "written naming (PNT)",
                                               "EBG" = NA,
                                               "ERM" = "written naming (VNT)",
                                               "GSH" = "aos",
                                               "IJN" = "written naming (PNT)",
                                               "JBN" = "aos",
                                               "JEE" = "written naming (PNT)",
                                               "JHR" = "spelling",
                                               "JJI" = "aos",
                                               "JPS" = "aos phase 1PNT phase 2",
                                               "JRA" = "written naming (PNT)",
                                               "JSS" = "written naming (VNT)",
                                               "JWE" = "written naming (PNT)",
                                               "KBG" = "syntactic",
                                               "LCR" = "written naming (VNT)",
                                               "LRW" = "written naming (PNT)",
                                               "MOR" = "written naming (VNT)",
                                               "MPI" = "written naming (VNT/PNT)",
                                               "MSM" = "aos",
                                               "MVR" = "written naming (VNT)",
                                               "NCG" = "written naming (PNT)",
                                               "RFH" = "written naming (PNT)",
                                               "RLN" = "oral letter fluency ph 1 (SMG ph 2)",
                                               "SFY" = NA,
                                               "SRI" = "aos",
                                               "SRR" = "semafore (stim both times)",
                                               "TBE" = "written naming (PNT)",
                                               "bnr" = "spelling",
                                               "cce" = "aos",
                                               "cdy" = "aos",
                                               "cke" = "written naming",
                                               "DDN" = NA,
                                               "DRY" = "aos",
                                               "DTL" = "written naming (VNT)",
                                               "GFS" = "written naming (PNT)",
                                               "HAH" = NA,
                                               "jjn" = "spelling",
                                               "jka" = "written naming (PNT)",
                                               "jrd" = "spelling",
                                               "jre" = "spelling",
                                               "kce" = "word written correctly",
                                               "KEY:" = NA,
                                               "lrl" = "spelling",
                                               "pzr" = "aos",
                                               "rbg" = "spelling (Spanish)",
                                               "rcl" = "oral letter fluency",
                                               "RJN" = NA,
                                               "rvt" = "aos",
                                               "RWT" = "written naming (VNT)",
                                               "SAS/SPA" = "syntactic (Spanish)came ph 1 only",
                                               "SCN" = NA,
                                               "skr" = "spelling",
                                               "slr" = "spelling",
                                               "tbd" = "spelling",
                                               "tbt" = "spelling",
                                               'AGS2989' = NA,
                                               "BSS7123" = NA,
                                               "BWS1830" = NA,
                                               "CSZ0789" = NA,
                                               "GFN6532" = NA,
                                               "JRK6031" = NA,
                                               "JSR9493" = NA,
                                               "JTR8536" = NA,
                                               "KGR8179" = NA,
                                               "MBR6656" = NA,
                                               "RBS8706" = NA,
                                               "RPI8252" = NA,
                                               "RSN9920" = NA,
                                               "SLR8021" = NA))



v$education <- revalue(v$speaker, c("ABK" = NA,
                                    "ACY" = 18,
                                    "AGG" = 20,
                                    "BIN" = 16,
                                    "BLR" = 16,
                                    "CBN" = NA,
                                    "CBT" = NA,
                                    "CCD" = NA,
                                    "CKI" = 18,
                                    "DCN" = 20,
                                    "DEK" = 18,
                                    "DME" = NA,
                                    "DNE" = 12,
                                    "DPD" = 17,
                                    "DPZ" = 16,
                                    "DRS" = 12,
                                    "DUE" = 18,
                                    "EAE" = 16,
                                    "EBG" = 20,
                                    "ERM" = 16,
                                    "GSH" = 20,
                                    "IJN" = 18,
                                    "JBN" = 20,
                                    "JEE" = 16,
                                    "JHR" = NA,
                                    "JJI" = 6,
                                    "JPS" = NA,
                                    "JRA" = 16,
                                    "JSS" = NA,
                                    "JWE" = 16,
                                    "KBG" = 14,
                                    "LCR" = 18,
                                    "LRW" = 16,
                                    "MOR" = 16,
                                    "MPI" = 16,
                                    "MSM" = 20,
                                    "MVR" = 15,
                                    "NCG" = 12,
                                    "RFH" = 16,
                                    "RLN" = 18,
                                    "SFY" = NA,
                                    "SRI" = 20,
                                    "SRR" = 10,
                                    "TBE" = 16,
                                    "bnr" = 16,
                                    "cce" = 12,
                                    "cdy" = NA,
                                    "cke" = 16,
                                    "DDN" = NA,
                                    "DRY" = 16,
                                    "DTL" = NA,
                                    "GFS" = NA,
                                    "HAH" = 18,
                                    "jjn" = 20,
                                    "jka" = 18,
                                    "jrd" = 16,
                                    "jre" = 18,
                                    "kce" = 16,
                                    "KEY:" = NA,
                                    "lrl" = 16,
                                    "pzr" = 12,
                                    "rbg" = 18,
                                    "rcl" = 18,
                                    "RJN" = 20,
                                    "rvt" = 20,
                                    "RWT" = 20,
                                    "SAS/SPA" = NA,
                                    "SCN" = NA,
                                    "skr" = 20,
                                    "slr" = 13.5,
                                    "tbd" = 18,
                                    "tbt" = 14,
                                    'AGS2989' = 13,
                                    "BSS7123" = 12,
                                    "BWS1830" = 18,
                                    "CSZ0789" = 12,
                                    "GFN6532" = NA,
                                    "JRK6031" = 12,
                                    "JSR9493" = NA,
                                    "JTR8536" = 14,
                                    "KGR8179" = NA,
                                    "MBR6656" = 16,
                                    "RBS8706" = NA,
                                    "RPI8252" = NA,
                                    "RSN9920" = NA,
                                    "SLR8021" = NA))




v$sessions_in_phase_1 <- revalue(v$speaker, c("ABK" = 12,
                                              "ACY" = 0,
                                              "AGG" = 10,
                                              "BIN" = 10,
                                              "BLR" = 14,
                                              "CBN" = 10,
                                              "CBT" = 10,
                                              "CCD" = 13,
                                              "CKI" = 10,
                                              "DCN" = 13,
                                              "DEK" = 15,
                                              "DME" = 10,
                                              "DNE" = 14,
                                              "DPD" = 12,
                                              "DPZ" = 10,
                                              "DRS" = 14,
                                              "DUE" = 14,
                                              "EAE" = 10,
                                              "EBG" = 0,
                                              "ERM" = 12,
                                              "GSH" = 10,
                                              "IJN" = 12,
                                              "JBN" = 13,
                                              "JEE" = 13,
                                              "JHR" = 9,
                                              "JJI" = 14,
                                              "JPS" = 14,
                                              "JRA" = 10,
                                              "JSS" = 13,
                                              "JWE" = 15,
                                              "KBG" = 14,
                                              "LCR" = 12,
                                              "LRW" = 14,
                                              "MOR" = 13,
                                              "MPI" = 11,
                                              "MSM" = 10,
                                              "MVR" = 10,
                                              "NCG" = 13,
                                              "RFH" = 13,
                                              "RLN" = 12,
                                              "SFY" = 0,
                                              "SRI" = 15,
                                              "SRR" = 14,
                                              "TBE" = 10,
                                              "bnr" = 15,
                                              "cce" = 15,
                                              "cdy" = 15,
                                              "cke" = 15,
                                              "DDN" = NA,
                                              "DRY" = 10,
                                              "DTL" = 10,
                                              "GFS" = 10,
                                              "HAH" = 0,
                                              "jjn" = 15,
                                              "jka" = 15,
                                              "jrd" = 15,
                                              "jre" = 15,
                                              "kce" = 15,
                                              "KEY:" = NA,
                                              "lrl" = 15,
                                              "pzr" = 15,
                                              "rbg" = 15,
                                              "rcl" = 15,
                                              "RJN" = 0,
                                              "rvt" = 15,
                                              "RWT" = 13,
                                              "SAS/SPA" = NA,
                                              "SCN" = 0,
                                              "skr" = 15,
                                              "slr" = 15,
                                              "tbd" = 15,
                                              "tbt" = 15,
                                              'AGS2989' = NA,
                                              "BSS7123" = NA,
                                              "BWS1830" = NA,
                                              "CSZ0789" = NA,
                                              "GFN6532" = NA,
                                              "JRK6031" = NA,
                                              "JSR9493" = NA,
                                              "JTR8536" = NA,
                                              "KGR8179" = NA,
                                              "MBR6656" = NA,
                                              "RBS8706" = NA,
                                              "RPI8252" = NA,
                                              "RSN9920" = NA,
                                              "SLR8021" = NA))





v$sessions_in_phase2 <- revalue(v$speaker, c("ABK" = 0,
                                             "ACY" = 0,
                                             "AGG" = 10,
                                             "BIN" = 10,
                                             "BLR" = 0,
                                             "CBN" = 10,
                                             "CBT" = 10,
                                             "CCD" = 10,
                                             "CKI" = 10,
                                             "DCN" = 10,
                                             "DEK" = 15,
                                             "DME" = 10,
                                             "DNE" = 13,
                                             "DPD" = 12,
                                             "DPZ" = 10,
                                             "DRS" = 10,
                                             "DUE" = 0,
                                             "EAE" = 2,
                                             "EBG" = 0,
                                             "ERM" = 0,
                                             "GSH" = 10,
                                             "IJN" = 13,
                                             "JBN" = 0,
                                             "JEE" = 12,
                                             "JHR" = 11,
                                             "JJI" = 12,
                                             "JPS" = 14,
                                             "JRA" = 10,
                                             "JSS" = 12,
                                             "JWE" = 12,
                                             "KBG" = 13,
                                             "LCR" = 12,
                                             "LRW" = 13,
                                             "MOR" = 12,
                                             "MPI" = 11,
                                             "MSM" = 10,
                                             "MVR" = 10,
                                             "NCG" = 13,
                                             "RFH" = 10,
                                             "RLN" = 13,
                                             "SFY" = 0,
                                             "SRI" = 14,
                                             "SRR" = 14,
                                             "TBE" = 10,
                                             "bnr" = 15,
                                             "cce" = 15,
                                             "cdy" = 15,
                                             "cke" = 15,
                                             "DDN" = NA,
                                             "DRY" = 10,
                                             "DTL" = 10,
                                             "GFS" = 0,
                                             "HAH" = 0,
                                             "jjn" = 15,
                                             "jka" = 15,
                                             "jrd" = 15,
                                             "jre" = 15,
                                             "kce" = 15,
                                             "KEY:" = NA,
                                             "lrl" = 15,
                                             "pzr" = 15,
                                             "rbg" = 15,
                                             "rcl" = 15,
                                             "RJN" = 0,
                                             "rvt" = 15,
                                             "RWT" = 12,
                                             "SAS/SPA" = NA,
                                             "SCN" = 0,
                                             "skr" = 15,
                                             "slr" = 15,
                                             "tbd" = 15,
                                             "tbt" = 15,
                                             'AGS2989' = NA,
                                             "BSS7123" = NA,
                                             "BWS1830" = NA,
                                             "CSZ0789" = NA,
                                             "GFN6532" = NA,
                                             "JRK6031" = NA,
                                             "JSR9493" = NA,
                                             "JTR8536" = NA,
                                             "KGR8179" = NA,
                                             "MBR6656" = NA,
                                             "RBS8706" = NA,
                                             "RPI8252" = NA,
                                             "RSN9920" = NA,
                                             "SLR8021" = NA))







v$gender <- revalue(v$speaker, c("ABK" = "F",
                                 "ACY" = "F",
                                 "AGG" = "M",
                                 "BIN" = "M",
                                 "BLR" = "F",
                                 "CBN" = "F",
                                 "CBT" = "M",
                                 "CCD" = "F",
                                 "CKI" = "F",
                                 "DCN" = "M",
                                 "DEK" = "M",
                                 "DME" = "F",
                                 "DNE" = "F",
                                 "DPD" = "M",
                                 "DPZ" = "M",
                                 "DRS" = "M",
                                 "DUE" = "F",
                                 "EAE" = "F",
                                 "EBG" = "M",
                                 "ERM" = "M",
                                 "GSH" = "M",
                                 "IJN" = "F",
                                 "JBN" = "M",
                                 "JEE" = "M",
                                 "JHR" = "F",
                                 "JJI" = "M",
                                 "JPS" = "F",
                                 "JRA" = "M",
                                 "JSS" = "M",
                                 "JWE" = "F",
                                 "KBG" = "M",
                                 "LCR" = "F",
                                 "LRW" = "F",
                                 "MOR" = "M",
                                 "MPI" = "M",
                                 "MSM" = "M",
                                 "MVR" = "M",
                                 "NCG" = "F",
                                 "RFH" = "M",
                                 "RLN" = "M",
                                 "SFY" = "F",
                                 "SRI" = "M",
                                 "SRR" = "F",
                                 "TBE" = "F",
                                 "bnr" = "F",
                                 "cce" = "F",
                                 "cdy" = "F",
                                 "cke" = "F",
                                 "DDN" = NA,
                                 "DRY" = "F",
                                 "DTL" = "F",
                                 "GFS" = "F",
                                 "HAH" = "M",
                                 "jjn" = "M",
                                 "jka" = "F",
                                 "jrd" = "M",
                                 "jre" = "M",
                                 "kce" = "F",
                                 "KEY:" = NA,
                                 "lrl" = "F",
                                 "pzr" = "F",
                                 "rbg" = "F",
                                 "rcl" = "M",
                                 "RJN" = "M",
                                 "rvt" = "M",
                                 "RWT" = "M",
                                 "SAS/SPA" = "F",
                                 "SCN" = "M",
                                 "skr" = "M",
                                 "slr" = "M",
                                 "tbd" = "M",
                                 "tbt" = "M",
                                 'AGS2989' = "M",
                                 "BSS7123" = "F",
                                 "BWS1830" = "M",
                                 "CSZ0789" = "F",
                                 "GFN6532" = "F",
                                 "JRK6031" = "F",
                                 "JSR9493" = "F",
                                 "JTR8536" = "M",
                                 "KGR8179" = "F",
                                 "MBR6656" = "M",
                                 "RBS8706" = NA,
                                 "RPI8252" = NA,
                                 "RSN9920" = NA,
                                 "SLR8021" = "M"))



v$onset_years <- revalue(v$speaker,c("ABK" = 6,
                                     "ACY" = 3,
                                     "AGG" = NA,
                                     "BIN" = 3,
                                     "BLR" = 1.5,
                                     "CBN" = 4,
                                     "CBT" = 3.5,
                                     "CCD" = 6.5,
                                     "CKI" = 2,
                                     "DCN" = 3,
                                     "DEK" = 7.5,
                                     "DME" = 2,
                                     "DNE" = 2.5,
                                     "DPD" = 8,
                                     "DPZ" = 6,
                                     "DRS" = 3,
                                     "DUE" = 9.5,
                                     "EAE" = 2.5,
                                     "EBG" = NA,
                                     "ERM" = 2.5,
                                     "GSH" = 6,
                                     "IJN" = 3,
                                     "JBN" = 2,
                                     "JEE" = 7,
                                     "JHR" = 1,
                                     "JJI" = 1.5,
                                     "JPS" = 1.5,
                                     "JRA" = 6,
                                     "JSS" = NA,
                                     "JWE" = 2.5,
                                     "KBG" = NA,
                                     "LCR" = 1.5,
                                     "LRW" = 4,
                                     "MOR" = 1,
                                     "MPI" = 10,
                                     "MSM" = 2,
                                     "MVR" = 4,
                                     "NCG" = 5.5,
                                     "RFH" = 10,
                                     "RLN" = 2.5,
                                     "SFY" = NA,
                                     "SRI" = 1.5,
                                     "SRR" = NA,
                                     "TBE" = 2.5,
                                     "bnr" = 10.5,
                                     "cce" = 9,
                                     "cdy" = 4,
                                     "cke" = 3,
                                     "DDN" = NA,
                                     "DRY" = 3.5,
                                     "DTL" = "2?",
                                     "GFS" = 3.5,
                                     "HAH" = 2.5,
                                     "jjn" = 2,
                                     "jka" = 3,
                                     "jrd" = 6,
                                     "jre" = 0.5,
                                     "kce" = 9.5,
                                     "KEY:" = NA,
                                     "lrl" = 5.5,
                                     "pzr" = 4,
                                     "rbg" = 6.5,
                                     "rcl" = 3.5,
                                     "RJN" = NA,
                                     "rvt" = 7,
                                     "RWT" = 10.5,
                                     "SAS/SPA" = NA,
                                     "SCN" = NA,
                                     "skr" = 4,
                                     "slr" = 2.5,
                                     "tbd" = 3,
                                     "tbt" = 1.5,
                                     'AGS2989' = NA,
                                     "BSS7123" = NA,
                                     "BWS1830" = NA,
                                     "CSZ0789" = NA,
                                     "GFN6532" = NA,
                                     "JRK6031" = NA,
                                     "JSR9493" = NA,
                                     "JTR8536" = NA,
                                     "KGR8179" = NA,
                                     "MBR6656" = NA,
                                     "RBS8706" = NA,
                                     "RPI8252" = NA,
                                     "RSN9920" = NA,
                                     "SLR8021" = NA))






v$age <- revalue(v$speaker, c("ABK" = 60,
                              "ACY" = 69,
                              "AGG" = 72,
                              "BIN" = 65,
                              "BLR" = 53,
                              "CBN" = 69,
                              "CBT" = 69,
                              "CCD" = 65,
                              "CKI" = 69,
                              "DCN" = 75,
                              "DEK" = 59,
                              "DME" = 66,
                              "DNE" = 73,
                              "DPD" = 73,
                              "DPZ" = 64,
                              "DRS" = 51,
                              "DUE" = 70,
                              "EAE" = 64,
                              "EBG" = 80,
                              "ERM" = 80,
                              "GSH" = 68,
                              "IJN" = 71,
                              "JBN" = 65,
                              "JEE" = 73,
                              "JHR" = 55,
                              "JJI" = 78,
                              "JPS" = 63,
                              "JRA" = 62,
                              "JSS" = 74,
                              "JWE" = 64,
                              "KBG" = 64,
                              "LCR" = 69,
                              "LRW" = 71,
                              "MOR" = 54,
                              "MPI" = 77,
                              "MSM" = 70,
                              "MVR" = 63,
                              "NCG" = 75,
                              "RFH" = 71,
                              "RLN" = 70,
                              "SFY" = NA,
                              "SRI" = 79,
                              "SRR" = 77,
                              "TBE" = 64,
                              "bnr" = 75,
                              "cce" = 74,
                              "cdy" = 74,
                              "cke" = 66,
                              "DDN" = NA,
                              "DRY" = 53,
                              "DTL" = 66,
                              "GFS" = 66,
                              "HAH" = 71,
                              "jjn" = 77,
                              "jka" = 68,
                              "jrd" = 63,
                              "jre" = 68,
                              "kce" = 68,
                              "KEY:" = NA,
                              "lrl" = 71,
                              "pzr" = 68,
                              "rbg" = 62,
                              "rcl" = 76,
                              "RJN" = NA,
                              "rvt" = 62,
                              "RWT" = 66,
                              "SAS/SPA" = 51,
                              "SCN" = NA,
                              "skr" = 73,
                              "slr" = 69,
                              "tbd" = 58,
                              "tbt" = 72,
                              'AGS2989' = 60,
                              "BSS7123" = 67,
                              "BWS1830" = 68,
                              "CSZ0789" = 74,
                              "GFN6532" = 76,
                              "JRK6031" = 75,
                              "JSR9493" = 59,
                              "JTR8536" = 75,
                              "KGR8179" = 59,
                              "MBR6656" = 71,
                              "RBS8706" = NA,
                              "RPI8252" = NA,
                              "RSN9920" = NA,
                              "SLR8021" = 72))





v$language_severity <- revalue(v$speaker, c("ABK" = 2,
                                            "ACY" = 1,
                                            "AGG" = 0.5,
                                            "BIN" = 1,
                                            "BLR" = 1,
                                            "CBN" = 2,
                                            "CBT" = 1,
                                            "CCD" = 2,
                                            "CKI" = 2,
                                            "DCN" = 3,
                                            "DEK" = 2,
                                            "DME" = 1,
                                            "DNE" = 2,
                                            "DPD" = 2,
                                            "DPZ" = 3,
                                            "DRS" = 0.5,
                                            "DUE" = 3,
                                            "EAE" = 3,
                                            "EBG" = NA,
                                            "ERM" = 2,
                                            "GSH" = 2,
                                            "IJN" = 2,
                                            "JBN" = 0.5,
                                            "JEE" = 3,
                                            "JHR" = 0.5,
                                            "JJI" = 2,
                                            "JPS" = 3,
                                            "JRA" = 3,
                                            "JSS" = 1,
                                            "JWE" = 1,
                                            "KBG" = 1,
                                            "LCR" = NA,
                                            "LRW" = 2,
                                            "MOR" = 2,
                                            "MPI" = 2,
                                            "MSM" = 0.5,
                                            "MVR" = 1,
                                            "NCG" = 2,
                                            "RFH" = 2,
                                            "RLN" = 0.5,
                                            "SFY" = NA,
                                            "SRI" = 1,
                                            "SRR" = NA,
                                            "TBE" = 1,
                                            "bnr" = 3,
                                            "cce" = 2,
                                            "cdy" = 1,
                                            "cke" = 1,
                                            "DDN" = NA,
                                            "DRY" = 0.5,
                                            "DTL" = 3,
                                            "GFS" = 3,
                                            "HAH" = NA,
                                            "jjn" = 2,
                                            "jka" = 2,
                                            "jrd" = 3,
                                            "jre" = 0.5,
                                            "kce" = 3,
                                            "KEY:" = NA,
                                            "lrl" = 2,
                                            "pzr" = 2,
                                            "rbg" = 2,
                                            "rcl" = 2,
                                            "RJN" = NA,
                                            "rvt" = 3,
                                            "RWT" = 3,
                                            "SAS/SPA" = NA,
                                            "SCN" = NA,
                                            "skr" = 3,
                                            "slr" = 1,
                                            "tbd" = 1,
                                            "tbt" = 0.5,
                                            'AGS2989' = NA,
                                            "BSS7123" = NA,
                                            "BWS1830" = NA,
                                            "CSZ0789" = NA,
                                            "GFN6532" = NA,
                                            "JRK6031" = NA,
                                            "JSR9493" = NA,
                                            "JTR8536" = NA,
                                            "KGR8179" = NA,
                                            "MBR6656" = NA,
                                            "RBS8706" = NA,
                                            "RPI8252" = NA,
                                            "RSN9920" = NA,
                                            "SLR8021" = NA))




#FTD-CDR
v$total_severity <- revalue(v$speaker, 
                            c("ABK" = 8,
                              "ACY" = 1.5,
                              "AGG" = 1.5,
                              "BIN" = 2,
                              "BLR" = 9.5,
                              "CBN" = 6,
                              "CBT" = 3.5,
                              "CCD" = 9,
                              "CKI" = 10,
                              "DCN" = 14,
                              "DEK" = 5.5,
                              "DME" = 3,
                              "DNE" = 7,
                              "DPD" = 5,
                              "DPZ" = 15,
                              "DRS" = 2,
                              "DUE" = 10,
                              "EAE" = 17.5,
                              "EBG" = NA,
                              "ERM" = 3,
                              "GSH" = NA,
                              "IJN" = 5,
                              "JBN" = 1,
                              "JEE" = 8,
                              "JHR" = 1.5,
                              "JJI" = 5.5,
                              "JPS" = 8,
                              "JRA" = 9.5,
                              "JSS" = 3,
                              "JWE" = 1,
                              "KBG" = 3,
                              "LCR" = NA,
                              "LRW" = 9,
                              "MOR" = 8,
                              "MPI" = 6.5,
                              "MSM" = 0.5,
                              "MVR" = 8.5,
                              "NCG" = 7.5,
                              "RFH" = 4,
                              "RLN" = 0.5,
                              "SFY" = NA,
                              "SRI" = 2,
                              "SRR" = NA,
                              "TBE" = 3.5,
                              "bnr" = 12,
                              "cce" = 3,
                              "cdy" = 1.5,
                              "cke" = 5,
                              "DDN" = NA,
                              "DRY" = 0.5,
                              "DTL" = 19,
                              "GFS" = 5,
                              "HAH" = NA,
                              "jjn" = 12,
                              "jka" = 6.5,
                              "jrd" = 17,
                              "jre" = 1,
                              "kce" = 18.5,
                              "KEY:" = NA,
                              "lrl" = 2.5,
                              "pzr" = NA,
                              "rbg" = 11.5,
                              "rcl" = 14,
                              "RJN" = NA,
                              "rvt" = NA,
                              "RWT" = 6,
                              "SAS/SPA" = NA,
                              "SCN" = NA,
                              "skr" = 5,
                              "slr" = 2.5,
                              "tbd" = 2.5,
                              "tbt" = 3,
                              'AGS2989' = NA,
                              "BSS7123" = NA,
                              "BWS1830" = NA,
                              "CSZ0789" = NA,
                              "GFN6532" = NA,
                              "JRK6031" = NA,
                              "JSR9493" = NA,
                              "JTR8536" = NA,
                              "KGR8179" = NA,
                              "MBR6656" = NA,
                              "RBS8706" = NA,
                              "RPI8252" = NA,
                              "RSN9920" = NA,
                              "SLR8021" = NA))



v$MRI <- revalue(v$speaker,c("ABK" = "Y",
                             "ACY" = "Y",
                             "AGG" = "Y",
                             "BIN" = "Y",
                             "BLR" = "Y",
                             "CBN" = "Y",
                             "CBT" = "Y",
                             "CCD" = "Y",
                             "CKI" = "Y",
                             "DCN" = "Y",
                             "DEK" = "Y",
                             "DME" = "Y",
                             "DNE" = "Ylater",
                             "DPD" = "Y",
                             "DPZ" = "Y",
                             "DRS" = "Y",
                             "DUE" = "Y",
                             "EAE" = "N",
                             "EBG" = "Y",
                             "ERM" = "Y",
                             "GSH" = "Y",
                             "IJN" = "Y",
                             "JBN" = "Y",
                             "JEE" = "N",
                             "JHR" = "Y",
                             "JJI" = "Y",
                             "JPS" = "Y",
                             "JRA" = "N",
                             "JSS" = "Y",
                             "JWE" = "Y",
                             "KBG" = "Y",
                             "LCR" = "Y",
                             "LRW" = "N",
                             "MOR" = "Y",
                             "MPI" = "N",
                             "MSM" = "Y",
                             "MVR" = "Y",
                             "NCG" = "Y",
                             "RFH" = "Y",
                             "RLN" = "Y",
                             "SFY" = "Y",
                             "SRI" = "Y",
                             "SRR" = "Y",
                             "TBE" = "Y",
                             "bnr" = "Y",
                             "cce" = "Y",
                             "cdy" = "N",
                             "cke" = "Y",
                             "DDN" = "Y",
                             "DRY" = "N",
                             "DTL" = "Y",
                             "GFS" = "Y",
                             "HAH" = "Y",
                             "jjn" = "Y",
                             "jka" = "Y",
                             "jrd" = "N",
                             "jre" = "Y",
                             "kce" = "Y",
                             "KEY:" = NA,
                             "lrl" = "N",
                             "pzr" = "?",
                             "rbg" = "Y",
                             "rcl" = "Y",
                             "RJN" = "Y",
                             "rvt" = "N",
                             "RWT" = "Y",
                             "SAS/SPA" = "Y",
                             "SCN" = "Y",
                             "skr" = "N",
                             "slr" = "Y",
                             "tbd" = "Y",
                             "tbt" = "N",
                             'AGS2989' = NA,
                             "BSS7123" = NA,
                             "BWS1830" = NA,
                             "CSZ0789" = NA,
                             "GFN6532" = NA,
                             "JRK6031" = NA,
                             "JSR9493" = NA,
                             "JTR8536" = NA,
                             "KGR8179" = NA,
                             "MBR6656" = NA,
                             "RBS8706" = NA,
                             "RPI8252" = NA,
                             "RSN9920" = NA,
                             "SLR8021" = NA))



v$segment <- revalue(v$label,c(
  'AA' =	'ɑ',
  'AE' =	'æ',
  'AH' =	'ʌ',
  'AO' =	'ɔ',
  'AW' =	'aʊ',
  'AX' =	'ə',
  'AXR' = 'ɚ',
  'AY' =	'aɪ',
  'EH' =	'ɛ',
  'ER' =	'ɝ',
  'EY' =	'eɪ',
  'IH' =	'ɪ',
  'IX' =	'ɨ',
  'IY' =	'i',
  'OW' =	'oʊ',
  'OY' =	'ɔɪ',
  'UH' =	'ʊ',
  'UW' =	'u',
  'UX' =	'ʉ',
  'B' =	'b',
  'CH' =	'tʃ',
  'D' =	'd',
  'DH' =	'ð',
  'DX' =	'ɾ',
  'EL' =	'l̩',
  'EM' =	'm̩',
  'EN' =	'n̩',
  'F' =	'f',
  'G' =	'ɡ',
  'HH' =	'h',
  'H' =	'h',
  'JH' =	'dʒ',
  'K' =	'k',
  'L' =	'l',
  'M' =	'm',
  'N' =	'n',
  'NX' =	'ŋ',
  'NG' =	'ŋ',
  'NX' =	'ɾ̃',
  'P' =	'p',
  'Q' =	'ʔ',
  'R' =	'ɹ',
  'S' =	's',
  'SH' =	'ʃ',
  'T' =	't',
  'TH' =	'θ',
  'V' =	'v',
  'W' =	'w',
  'WH' =	'ʍ',
  'Y' =	'j',
  'Z' =	'z',
  'ZH' =	'ʒ'))

v$phone <- revalue(v$label,c(
  'AA' = 'V',
  'AE' = 'V',
  'AH' = 'V',
  'AO' = 'V',
  'AW' = 'V',
  'AX' = 'V',
  'AXR' = 'V',
  'AY' = 'V',
  'EH' = 'V',
  'ER' = 'V',
  'EY' = 'V',
  'IH' = 'V',
  'IX' = 'V',
  'IY' = 'V',
  'OW' = 'V',
  'OY' = 'V',
  'UH' = 'V',
  'UW' = 'V',
  'UX' = 'V',
  'B' = 'C',
  'CH' = 'C',
  'D' = 'C',
  'DH' = 'C',
  'DX' = 'C',
  'EL' = 'C',
  'EM' = 'C',
  'EN' = 'C',
  'F' = 'C',
  'G' = 'C',
  'HH' = 'C', 
  'H' = 'C',
  'JH' = 'C',
  'K' = 'C',
  'L' = 'C',
  'M' = 'C',
  'N' = 'C',
  'NX' = 'C', 
  'NG' = 'C',
  'NX' = 'C',
  'P' = 'C',
  'Q' = 'C',
  'R' = 'C',
  'S' = 'C',
  'SH' = 'C',
  'T' = 'C',
  'TH' = 'C',
  'V' = 'C',
  'W' = 'C',
  'WH' = 'C',
  'Y' = 'C',
  'Z' = 'C',
  'ZH' = 'C'))

v$pausedur <- revalue(v$speaker, c("ABK" = 12480,
                                   "ACY" = 18813,
                                   "AGG" = 14513,
                                   "AGS2989" = 15068,
                                   "ASR" = 18628,
                                   "BIN" = 11592,
                                   "BLR" = 263,
                                   "BSS7123" = 14253,
                                   "BWS1830" = 14681,
                                   "CBN" = 17198,
                                   "CBT" = 11581,
                                   "CCD" = 10742,
                                   "CKI" = 1907,
                                   "CSZ0789" = 9684,
                                   "DCN" = 15589,
                                   "DEK" = 597,
                                   "DME" = 17413,
                                   "DNE" = 1274,
                                   "DPD" = 9350,
                                   "DPZ" = 6112,
                                   "DRS" = 2031,
                                   "DUE" = 4472,
                                   "EAE" = 705,
                                   "EBG" = 7104,
                                   "ERM" = 5593,
                                   "GFN6532" = 12808,
                                   "GSH" = 13363,
                                   "IJN" = 779,
                                   "JBN" = 7122,
                                   "JEE" = 4150,
                                   "JHR" = 14190,
                                   "JJI" = 10290,
                                   "JPS" = 16704,
                                   "JRA" = 21672,
                                   "JRK6031" = 12947,
                                   "JSR9493" = 9101,
                                   "JSS" = 12713,
                                   "JTR8536" = 14282,
                                   "JWE" = 250,
                                   "KBG" = 15156,
                                   "KGR8179" = 7425,
                                   "LCR" = 14699,
                                   "LRW" = 6773,
                                   "MBR6656" = 10838,
                                   "MOR" = 13990,
                                   "MPI" = 5597,
                                   "MSM" = 10939,
                                   "MVR" = 11008,
                                   "NCG" = 987,
                                   "RBS8706" = 15626,
                                   "RFH" = 1016,
                                   "RLN" = 3029,
                                   "RPI8252" = 5112,
                                   "RSN9920" = 24035,
                                   "SFY" = 14754,
                                   "SLR8021" = 10147,
                                   "SRI" = 1803,
                                   "SRR" = 11428,
                                   "TBE" = 15123))



# CLEANING THE DATABASE FROM REPEATED INFORMATION -------------------------

# "ABK_5-16-16_CookieTheft1"                                      
# "ABK_5-16-16_CookieTheft2"                                     
# "ABK_T1_8-1-16_Cookie1"                                         
# "ABK_T1_8-1-16_Cookie2"                                        
# "ABK_T2_8-17-16_Cookie_1"                                       
# "ABK_T2_8-17-16_Cookie_2"                                      
# "ABK_T2_8-17-16_Cookie_3"                                       
# "ACY_12-8-16_CookieTheft"                                      
# "AGG_02-09-17_Cookie_mp3_1"                                     
# "AGG_02-09-17_Cookie_mp3_2"                                    
# "AGG_06-02-17_CookieTheft_mp3_1"                               
# "AGG_06-02-17_CookieTheft_mp3_2"                               
# "AGG_06-02-17_CookieTheft_mp3_3"                                                    
# "AGG_10-26-17_Cookie_mp3_1"                                     
# "AGG_10-26-17_Cookie_mp3_2"                                    
# "AGG_10-26-17_Cookie_mp3_3"                                     
# "AGG_10-26-17_Cookie_mp3_4"                                    
# "AGS2989_10_5_2016_ct_m4a_"                                                            
# "ASR_09-18-17_EvalContinuedCookie_at_6_mins_mp3_1"              
# "ASR_09-18-17_EvalContinuedCookie_at_6_mins_mp3_2"             
# "BIN_03-27-17_Cookie_Theft_1"                                   
# "BIN_03-27-17_Cookie_Theft_2"                                  
# "BIN_04-06-17_Cookie_Theft_1"                                   
# "BIN_04-06-17_Cookie_Theft_2"                                  
# "BIN_1-24-17_EvaluationStoryCookie_at_5min18sec_mp3_"           
# "BLR_10-5-15_CookieTheft1"                                      
# "BLR_10-5-15_CookieTheft2"                                     
# "BLR_10-5-15_CookieTheft3"                                      
# "BSS7123_7_7_2017_CT_m4a_"                                     
# "BWS1830_3_25_16_COOKIE_THEFT_"                                
# "CBN_04-03-17_ApraxiaBatteryCookieat12min_mp3_1"               
# "CBN_04-03-17_ApraxiaBatteryCookieat12min_mp3_2"                
# "CBN_04-03-17_ApraxiaBatteryCookieat12min_mp3_3"               
# "CBN_2-2-17_Cookie_mp3_1"                                      
# "CBN_2-2-17_Cookie_mp3_2"                                       
# "CBN_2-2-17_Cookie_mp3_3"                                      
# "CBT_09-22-17_ApraxiaBatteryCookieat9min20sec_mp3_1"           
# "CBT_09-22-17_ApraxiaBatteryCookieat9min20sec_mp3_2"            
# "CCD_08-16-17_Cookie_mp3_1"                                    
# "CCD_08-16-17_Cookie_mp3_2"                                     
# "CCD_11-10-17-EvalCookie_mp3_"                                 
# "CKI_4-22-16_CookieTheft1"                                     
# "CKI_4-22-16_CookieTheft2"                                      
# "CKI_T1_6-20-16_Cookie1"                                       
# "CKI_T1_6-20-16_Cookie2"                                        
# "CKI_T2_6-29-16_Cookie1"                                       
# "CKI_T2_6-29-16_Cookie2"                                        
# "CKI_T2_6-29-16_Cookie3"                                       
# "CSZ0789_CT_m4a_"                                               
# "DCN_10-31-16_Cookie_Theft_mp3_1"                               
# "DCN_10-31-16_Cookie_Theft_mp3_2"                              
# "DEK_4-5-16_CookieTheft1"                                       
# "DEK_4-5-16_CookieTheft2"                                      
# "DEK_T1_6-20-16_Cookie_1"                                       
# "DEK_T1_6-20-16_Cookie_2"                                      
# "DEK_T2_7-7-16_Cookie_1"                                        
# "DEK_T2_7-7-16_Cookie_2"                                       
# "DEK_T2_7-7-16_Cookie_3"                                        
# "DME_03-07-17_CookieTheft_mp3_1"                               
# "DME_03-07-17_CookieTheft_mp3_2"                                
# "DME_03-07-17_CookieTheft_mp3_3"                               
# "DME_03-07-17_CookieTheft_mp3_4"                                
# "DME_07-10-17_ApraxiaBatteryCookieat12min10sec_mp3_1"          
# "DME_07-10-17_ApraxiaBatteryCookieat12min10sec_mp3_2"           
# "DNE_10-27-15_CookieTheft"                                     
# "DNE_T1_1-11-16_Cookie_1"                                       
# "DNE_T1_1-11-16_Cookie_2"                                      
# "DNE_T2_1-28-16_Cookie_"                                        
# "DPD_2-4-16_CookieTheft1"                                      
# "DPD_2-4-16_CookieTheft2"                                       
# "DPD_2-4-16_CookieTheft3"                                      
# "DPZ_2-29-16_CookieTheft"                                       
# "DRS_T1_9-10-15_Cookie"                                         
# "DRS_T2_10-1-15_Cookie_"                                       
# "DUE_10-6-15_CookieTheft1"                                      
# "DUE_10-6-15_CookieTheft2"                                     
# "DUE_T1_12-01-15_Cookie_"                                       
# "DUE_T2_12-17-15_Cookie_1"                                     
# "DUE_T2_12-17-15_Cookie_2"                                      
# "EAE_10-26-15_CookieTheft"                                     
# "EAE_T1_2-5-16_Cookie_1"                                        
# "EAE_T1_2-5-16_Cookie_2"                                       
# "EAE_T2_02-19-16_Cookie_1"                                      
# "EAE_T2_02-19-16_Cookie_2"                                     
# "EBG_9-9-15_CookieTheft1"                                       
# "EBG_9-9-15_CookieTheft2"                                      
# "ERM_11-23-15_CookieTheft"                                      
# "ERM_T1_2-12-16_Cookie_1"                                      
# "ERM_T1_2-12-16_Cookie_2"                                       
# "ERM_T2_3-02-16_Cookie_1"                                      
# "ERM_T2_3-02-16_Cookie_2"                                       
# "GFN6532_CookieTheft_8_5_2016_m4a_1"                           
# "GFN6532_CookieTheft_8_5_2016_m4a_2"                            
# "GSH_02-13-17_Cookie_Theft_1"                                  
# "GSH_02-13-17_Cookie_Theft_2"                                   
# "GSH_02-13-17_Cookie_Theft_3"                                  
# "GSH_02-24-17_CookieTheft_mp3_1"                               
# "GSH_02-24-17_CookieTheft_mp3_2"                                
# "GSH_02-24-17_CookieTheft_mp3_3"                               
# "GSH_02-24-17_CookieTheft_mp3_4"                                
# "GSH_02-24-17_CookieTheft_mp3_5"                               
# "GSH_10-27-16_EvalCookie_mp3_1"                                
# "GSH_10-27-16_EvalCookie_mp3_2"                                 
# "GSH_10-27-16_EvalCookie_mp3_3"                                
# "IJN_6-13-16_CookieTheft1"                                     
# "IJN_6-13-16_CookieTheft2"                                      
# "IJN_T1_10-20-16_Cookie_1"                                     
# "IJN_T1_10-20-16_Cookie_2"                                      
# "IJN_T2_11-03-16_Cookie_1"                                     
# "IJN_T2_11-03-16_Cookie_2"                                      
# "JBN_3-8-16_CookieTheft1"                                      
# "JBN_3-8-16_CookieTheft2"                                       
# "JBN_T1_6-21-16_Cookie_"                                       
# "JBN_T2_7-6-16_Cookie_1"                                        
# "JBN_T2_7-6-16_Cookie_2"                                       
# "JEE_6-9-16_CookieTheft1"                                       
# "JEE_6-9-16_CookieTheft2"                                      
# "JEE_T1_9-6-16_Cookie_1"                                        
# "JEE_T2_9-22-16_Cookie_1"                                      
# "JEE_T2_9-22-16_Cookie_2"                                       
# "JHR_03-20-17_CookieTheft_mp3_"                                
# "JJI_T1_9-11-15_Cookie1"                                       
# "JJI_T1_9-11-15_Cookie2"                                        
# "JJI_T2_9-29-15_Cookie_1"                                      
# "JJI_T2_9-29-15_Cookie_2"                                       
# "JPS_12-4-15_CookieTheft"                                      
# "JRA_9-28-15_CookieTheft1"                                      
# "JRK6031_CookieTheft_8_3_2016_1"                               
# "JRK6031_CookieTheft_8_3_2016_2"                                
# "JSR9493_6_19_2017_CT_m4a_"                                    
# "JSS_08-21-17_EvalContinuedPt2Cookieat9min_mp3_1"              
# "JSS_08-21-17_EvalContinuedPt2Cookieat9min_mp3_2"
# "JTR8536_2_3_2017_CT_m4a_1"                                    
# "JTR8536_2_3_2017_CT_m4a_2"                                     
# "JWE_9-30-15_CookieTheft"                                      
# "KBG_05-12-17_ApraxiaBatteryCookie3min30sec_mp3_"               
# "KBG_08-07-17_CookieTheft_mp3_1"                                
# "KBG_08-07-17_CookieTheft_mp3_2"                               
# "KGR8179_CookieTheft_8_3_2016_1"                                
# "KGR8179_CookieTheft_8_3_2016_2"                               
# "LCR_08-08-17_Cookie_mp3_1"                                     
# "LCR_08-08-17_Cookie_mp3_2"                                    
# "LCR_08-08-17_Cookie_mp3_3"                                     
# "LCR_10-17-17_EvalCookie_mp3_1"                                 
# "LCR_10-17-17_EvalCookie_mp3_2"                                
# "LCR_10-17-17_EvalCookie_mp3_3"                                 
# "LRW_1-14-16_CookieTheft1"                                      
# "LRW_1-14-16_CookieTheft2"                                     
# "LRW_1-14-16_CookieTheft3"                                      
# "MBR6656_11_1_2017_CT_m4a_1"                                   
# "MBR6656_11_1_2017_CT_m4a_2"                                   
# "MOR_09-05-17_Cookie_mp3_1"                                    
# "MOR_09-05-17_Cookie_mp3_2"                                     
# "MPI_2-18-16_CookieTheft"                                      
# "MPI_T1_6-01-16_Cookie_1"                                       
# "MPI_T1_6-01-16_Cookie_2"                                      
# "MPI_T2_6-15-16_Cookie_1"                                       
# "MPI_T2_6-15-16_Cookie_2"                                      
# "MPI_T2_6-15-16_Cookie_3"                                       
# "MSM_11-14-16_StoryEvaluationCookieat3min17sec_mp3_1"          
# "MSM_11-14-16_StoryEvaluationCookieat3min17sec_mp3_2"           
# "MVR_9-9-16_Evaluation_Cookie_mp3_1"                           
# "MVR_9-9-16_Evaluation_Cookie_mp3_2" 
# "NCG_9-24-15_CookieTheft"                                      
# "NCG_T1_9-24-15_Cookie"                                         
# "NCG_T2_10-21-15_Cookie_"                                      
# "RBS8706_12_2_2016_CT_m4a_"                                     
# "RFH_10-8-15_CookieTheft1"                                      
# "RFH_10-8-15_CookieTheft2"                                     
# "RFH_T1_1-5-16_Cookie_1"                                        
# "RFH_T1_1-5-16_Cookie_2"                                       
# "RFH_T2_1-21-16_Cookie_"                                        
# "RLN_12-16-15_CookieTheft1"                                    
# "RLN_12-16-15_CookieTheft2"                                     
# "RPI8252_11_14_2016_CT_m4a_"                                   
# "RSN9920_9_26_2016_CT_m4a_1"                                   
# "SFY_09-23-16_EvalCircusCookie3min50sec_mp3_"                  
# "SLR8021_CookieTheft_7_29_2016_"                               
# "SRI_6-7-16_CookieTheft1"                                      
# "SRI_6-7-16_CookieTheft2"                                       
# "SRI_T1_9-26-16_Cookie_2"                                      
# "SRI_T1_9-26-16_Cookie_3"                                       
# "SRI_T1_9-26-16_Cookie_4"                                      
# "SRI_T2_10-14-16_Cookie_1"                                      
# "SRI_T2_10-14-16_Cookie_2"                                     
# "SRI_T2_10-14-16_Cookie_3"                                      
# "SRR_10-26-17_EvalCookie_mp3_"                                 
# "TBE_05-01-17_CookieTheft_mp3_1"                               
# "TBE_05-01-17_CookieTheft_mp3_2"                                
# "TBE_5-11-17Cookie_mp3_1"                                      
# "TBE_5-11-17Cookie_mp3_2"                                       
# "TBE_5-11-17Cookie_mp3_3"  
                   


removerows= c("AGG_02-09-17_Cookie_mp3_mono1_16000",
"AGG_02-09-17_Cookie_mp3_mono2_16000",
"AGG_06-02-17_CookieTheft_mp3_mono1_16000",
"AGG_06-02-17_CookieTheft_mp3_mono2_16000",
"AGG_06-02-17_CookieTheft_mp3_mono3_16000",
"AGG_10-26-17_Cookie_mp3_mono1_16000",
"AGG_10-26-17_Cookie_mp3_mono2_16000",
"AGG_10-26-17_Cookie_mp3_mono3_16000",
"AGG_10-26-17_Cookie_mp3_mono4_16000",
"AGS2989_10_5_2016_ct_m4a_mono_16000",
"ASR_09-18-17_EvalContinuedCookie_at_6_mins_mp3_mono1_16000",
"ASR_09-18-17_EvalContinuedCookie_at_6_mins_mp3_mono2_16000",
"BIN_03-27-17_Cookie_Theft_mono1_16000",
"BIN_03-27-17_Cookie_Theft_mono2_16000",
"BIN_04-06-17_Cookie_Theft_mono1_16000",
"BIN_04-06-17_Cookie_Theft_mono2_16000",
"BIN_1-24-17_EvaluationStoryCookie_at_5min18sec_mp3_mono_16000",
"BSS7123_7_7_2017_CT_m4a_mono_16000",
"BWS1830_3_25_16_COOKIE_THEFT_mono_16000",
"CBN_04-03-17_ApraxiaBatteryCookieat12min_mp3_mono1_16000",
"CBN_04-03-17_ApraxiaBatteryCookieat12min_mp3_mono2_16000",
"CBN_04-03-17_ApraxiaBatteryCookieat12min_mp3_mono3_16000",
"CBN_2-2-17_Cookie_mp3_mono1_16000",
"CBN_2-2-17_Cookie_mp3_mono2_16000",
"CBN_2-2-17_Cookie_mp3_mono3_16000",
"CBT_09-22-17_ApraxiaBatteryCookieat9min20sec_mp3_mono1_16000",
"CBT_09-22-17_ApraxiaBatteryCookieat9min20sec_mp3_mono2_16000",
"CCD_08-16-17_Cookie_mp3_mono1_16000",
"CCD_08-16-17_Cookie_mp3_mono2_16000",
"CCD_11-10-17-EvalCookie_mp3_mono_16000",
"CSZ0789_CT_m4a_mono_16000",
"DCN_10-31-16_Cookie_Theft_mp3_mono1_16000",
"DCN_10-31-16_Cookie_Theft_mp3_mono2_16000",
"DME_03-07-17_CookieTheft_mp3_mono1_16000",
"DME_03-07-17_CookieTheft_mp3_mono2_16000",
"DME_03-07-17_CookieTheft_mp3_mono3_16000",
"DME_03-07-17_CookieTheft_mp3_mono4_16000",
"DME_07-10-17_ApraxiaBatteryCookieat12min10sec_mp3_mono1_16000",
"DME_07-10-17_ApraxiaBatteryCookieat12min10sec_mp3_mono2_16000",
"GFN6532_CookieTheft_8_5_2016_m4a_mono1_16000",
"GFN6532_CookieTheft_8_5_2016_m4a_mono2_16000",
"GSH_02-13-17_Cookie_Theft_mono1_16000",
"GSH_02-13-17_Cookie_Theft_mono2_16000",
"GSH_02-13-17_Cookie_Theft_mono3_16000",
"GSH_02-24-17_CookieTheft_mp3_mono1_16000",
"GSH_02-24-17_CookieTheft_mp3_mono2_16000",
"GSH_02-24-17_CookieTheft_mp3_mono3_16000",
"GSH_02-24-17_CookieTheft_mp3_mono4_16000",
"GSH_02-24-17_CookieTheft_mp3_mono5_16000",
"GSH_10-27-16_EvalCookie_mp3_mono1_16000",
"GSH_10-27-16_EvalCookie_mp3_mono2_16000",
"GSH_10-27-16_EvalCookie_mp3_mono3_16000",
"JHR_03-20-17_CookieTheft_mp3_mono_16000",
"JRK6031_CookieTheft_8_3_2016_mono1_16000",
"JRK6031_CookieTheft_8_3_2016_mono2_16000",
"JSR9493_6_19_2017_CT_m4a_mono_16000",
"JSS_08-21-17_EvalContinuedPt2Cookieat9min_mp3_mono1_16000",
"JSS_08-21-17_EvalContinuedPt2Cookieat9min_mp3_mono2_16000",
"JTR8536_2_3_2017_CT_m4a_mono1_16000",
"JTR8536_2_3_2017_CT_m4a_mono2_16000",
"KBG_05-12-17_ApraxiaBatteryCookie3min30sec_mp3_mono_16000",
"KBG_08-07-17_CookieTheft_mp3_mono1_16000",
"KBG_08-07-17_CookieTheft_mp3_mono2_16000",
"KGR8179_CookieTheft_8_3_2016_mono1_16000",
"KGR8179_CookieTheft_8_3_2016_mono2_16000",
"LCR_08-08-17_Cookie_mp3_mono1_16000",
"LCR_08-08-17_Cookie_mp3_mono2_16000",
"LCR_08-08-17_Cookie_mp3_mono3_16000",
"LCR_10-17-17_EvalCookie_mp3_mono1_16000",
"LCR_10-17-17_EvalCookie_mp3_mono2_16000",
"LCR_10-17-17_EvalCookie_mp3_mono3_16000",
"MBR6656_11_1_2017_CT_m4a_mono1_16000",
"MBR6656_11_1_2017_CT_m4a_mono2_16000",
"MOR_09-05-17_Cookie_mp3_mono1_16000",
"MOR_09-05-17_Cookie_mp3_mono2_16000",
"TBE_05-01-17_CookieTheft_mp3_mono1_16000",
"TBE_05-01-17_CookieTheft_mp3_mono2_16000",
"SRR_10-26-17_EvalCookie_mp3_mono_16000",
"SLR8021_CookieTheft_7_29_2016_mono_16000",
"SFY_09-23-16_EvalCircusCookie3min50sec_mp3_mono_16000",
"RSN9920_9_26_2016_CT_m4a_mono1_16000",
"RPI8252_11_14_2016_CT_m4a_mono_16000",
"RBS8706_12_2_2016_CT_m4a_mono_16000",
"MSM_11-14-16_StoryEvaluationCookieat3min17sec_mp3_mono1_16000",
"MSM_11-14-16_StoryEvaluationCookieat3min17sec_mp3_mono2_16000",
"MVR_9-9-16_Evaluation_Cookie_mp3_mono1_16000",
"MVR_9-9-16_Evaluation_Cookie_mp3_mono2_16000",
"TBE_5-11-17Cookie_mp3_mono1_16000",
"TBE_5-11-17Cookie_mp3_mono2_16000",
"TBE_5-11-17Cookie_mp3_mono3_16000",
"DRS_9-10-15_CookieTheft",
"JJI_9-11-15_CookieTheft1",
"JJI_9-11-15_CookieTheft2")

# removing those that I do not know there variant
unknown_variant = c('BWS1830',
'CSZ0789',
'GFN6532',
'JTR8536',
'JRK6031',
'RPI8252',
'RSN9920',
'RBS8706',  
'MBR6656',
'ASR')



write.csv(v, "phone_processed.csv")

levels(v$speaker)
table(v$speaker, v$variant)


# Mean Length of Words with respect to utterance duration
v$MLW <- as.integer(v$words)/as.integer(v$ut_dur)
# Mean Length of Characters with respect to utterance duration
v$MLC <- as.integer(v$words)/as.integer(v$ut_dur)
# Charecters Per Word
v$CPW <- as.integer(v$words)/as.integer(v$characters)

a=tapply(v$duration.1, list(v$speaker, v$label), mean)
a = data.frame(a)
a[31]
